### ISSUE TITLE
Input Conflict with SponsorBlock

### ISSUE THREAD

**Issue by AcesFullOfKings** [ArthurCose/YouTube-Control-Fix#3]
When submitting segments to [SponsorBlock](https://sponsor.ajay.app/), the SponsorBlock UI prompts users to enter timestamps or chapter names via text boxes overlaid over the video. These text boxes allow for free text entry, and often need slight tweaks to timestamps by using the left and right arrows to navigate the text, or need me to enter spaces e.g. in names of user-submitted chapters. However, since the YouTube Control Fix update in February, it appears to intercept these keystrokes, rendering the arrow keys and spacebar non-functional within SponsorBlock text boxes.

Could an exception be implemented so that keystrokes are not captured when a text box within SponsorBlock is focused?

**Comment by ArthurCose** [comment]
Noticed this late, but I've added a blacklist for `<input>` and `<textarea>` elements which should fix this. It'll take a few days for the change to go through review for Chrome and Firefox
